"""Receive messages over from RabbitMQ and send them over the websocket."""

import sys

import pika
import uwsgi


def application(env, start_response):
    """Setup the Websocket Server and read messages off the queue."""
    connection = pika.BlockingConnection(
    pika.ConnectionParameters(host='192.168.99.102')
    )
    channel = connection.channel()

    exchange = env['PATH_INFO'].replace('/', '')

    channel.exchange_declare(
        exchange=exchange, exchange_type='fanout'
    )

    # exclusive means the queue should be deleted once the connection is closed
    result = channel.queue_declare(queue='',exclusive=True)
    queue_name = result.method.queue  # random queue name generated by RabbitMQ
    print(queue_name)

    channel.queue_bind(exchange=exchange, queue=queue_name)

    uwsgi.websocket_handshake(
        env['HTTP_SEC_WEBSOCKET_KEY'],
        env.get('HTTP_ORIGIN', '')
    )

    def keepalive():
        """Keep the websocket connection alive (called every 30 seconds)."""
        print('PING/PONG...')
        try:
            uwsgi.websocket_recv_nb()
            #print(dir(connection))
            connection.sleep(3)
            keepalive()
        except OSError as error:
            print(error)
            sys.exit(1) # Kill process and force uWSGI to Respawn

    

    while True:
        for method_frame, _, body in channel.consume(queue_name):
            try:
                print("----------------------------")
                print(body)
                uwsgi.websocket_send(body)
                keepalive()
            except OSError as error:
                print(error)
                sys.exit(1)  # Force uWSGI to Respawn
            else:
                # acknowledge the message
                channel.basic_ack(method_frame.delivery_tag)
